pub fn typescript_contracts() -> &'static str {
    r#"// Generated by rp-engine-core. Do not edit.
export type DiagnosticLevel = 'debug' | 'info' | 'warn' | 'error';
export type HostEventV3 =
  | { type: 'bootstrap'; appVersion: string; language: string; port: number }
  | { type: 'uiPrimary' | 'uiToggleMicrophone' | 'pageHide' | 'ownershipAcquired' | 'ownershipDenied' | 'ownershipReleased' | 'transportOpened' }
  | { type: 'uiLanguage'; language: string }
  | { type: 'uiPort'; port: number }
  | { type: 'uiModelAction'; modelId: string; action: 'download' | 'cancel' | 'delete' }
  | { type: 'ownershipOther'; active: boolean; phase?: string }
  | { type: 'modelsSnapshot'; models: ModelStatusSnapshot[] }
  | { type: 'modelStatus' | 'runtimeProgress'; status: ModelStatusSnapshot }
  | { type: 'modelFailed'; modelId: string; message: string }
  | { type: 'modelCleanupCompleted'; modelId: string; removed: boolean }
  | { type: 'modelCleanupFailed'; modelId: string; message: string }
  | { type: 'runtimeLoaded'; operationId: number; expressionTags: string[] }
  | { type: 'runtimeFailed'; operationId: number; message: string; details?: unknown }
  | { type: 'microphoneEnabled' | 'microphoneDisabled' }
  | { type: 'microphoneFailed' | 'transportError'; message: string }
  | { type: 'transportMessage'; raw: string }
  | { type: 'transportClosed'; code?: number; reason?: string }
  | { type: 'timerFired'; timerId: string }
  | { type: 'captureLevel'; requestId: string; seconds: number; peak: number; rms: number }
  | { type: 'captureState'; requestId: string; state: string; seconds: number; autoEndEnabled: boolean; message?: string }
  | { type: 'captureFailed'; requestId: string; message: string }
  | { type: 'sttCompleted'; operationId: number; text: string; elapsedMs: number }
  | { type: 'sttFailed' | 'gemmaFailed' | 'ttsFailed'; operationId: number; message: string }
  | { type: 'gemmaDelta'; operationId: number; chunk: string }
  | { type: 'gemmaCompleted'; operationId: number; response: string; tokenCount: number; elapsedMs: number };

export type HostAudioEventV3 =
  | { type: 'captureCompleted'; requestId: string }
  | { type: 'ttsCompleted'; operationId: number; sampleRate: number; duration: number; elapsedMs: number };

export type CoreEffectV3 =
  | { type: 'transportConnect'; port: number; attempt: number }
  | { type: 'transportDisconnect'; reason: string }
  | { type: 'transportSend'; messageType: string; payload: Record<string, unknown>; sessionId?: string }
  | { type: 'scheduleTimer'; timerId: string; delayMs: number }
  | { type: 'cancelTimer'; timerId: string }
  | { type: 'ownershipAcquire' | 'ownershipRelease' | 'modelsRefresh' | 'runtimesDispose' | 'microphoneEnable' | 'microphoneDisable' }
  | { type: 'ownershipPhase'; phase: string }
  | { type: 'modelDownload' | 'modelCancel' | 'modelDelete'; modelId: string }
  | { type: 'modelCleanup'; modelId: string }
  | { type: 'runtimesLoad'; operationId: number; language: string; defaultVoice: string }
  | { type: 'captureStart' | 'captureStop' | 'captureCancel'; requestId: string }
  | { type: 'sttInvoke'; operationId: number; bufferId: number; language: string }
  | { type: 'gemmaInvoke'; operationId: number; system: string; user: string; history: Array<{ role: 'user' | 'assistant'; content: string }> }
  | { type: 'gemmaCancel'; operationId: number }
  | { type: 'ttsInvoke'; operationId: number; text: string; language: string; voice: string; segmentSequence: number }
  | { type: 'replyAudioTransport'; transportId: number }
  | { type: 'diagnostic'; level: DiagnosticLevel; category: string; message: string; details?: unknown; key?: string }
  | { type: 'render'; viewModel: AppViewModelV3 };

export interface EffectBatchV3 { abiVersion: 3; effects: CoreEffectV3[] }
export interface ModelStatusSnapshot { id: string; name: string; phase: string; progress: number; downloadedBytes: number; totalBytes: number; isResuming?: boolean; bytesPerSecond?: number; etaSeconds?: number; error?: string; runtimePhase?: 'loading' | 'ready' | 'error'; runtimeProgress?: number; runtimeError?: string }
export interface ModelViewV3 { id: string; role: string; name: string; status: string; transfer: string; progress: number; showProgress: boolean; action: 'download' | 'cancel' | 'delete'; actionLabel: string; disabled: boolean }
export interface AppViewModelV3 {
  connection: { state: string; label: string; connected: boolean };
  primary: { label: string; detail: string; disabled: boolean; progress?: number; indeterminate: boolean };
  ownerNotice: { visible: boolean; text: string };
  microphone: { enabled: boolean; label: string; disabled: boolean };
  settings: { language: string; port: number; languageDisabled: boolean; portDisabled: boolean; languages: Array<{ value: string; label: string }> };
  models: ModelViewV3[];
  service: { phase: string; ready: boolean };
  capacity: { queueDepth: number; queueLimit: number; acceptingRequests: boolean };
}

export type WorkerRequestV2 =
  | { type: 'load'; operationId: number; language?: string; voice?: string }
  | { type: 'generate'; operationId: number; system: string; user: string; history: Array<{ role: 'user' | 'assistant'; content: string }> }
  | { type: 'transcribe'; operationId: number; language: string; samples: Float32Array }
  | { type: 'synthesize'; operationId: number; text: string; language: string; voice: string }
  | { type: 'cancel'; operationId: number };
export type WorkerResultV2 =
  | { type: 'loaded'; operationId: number; expressionTags?: string[] }
  | { type: 'chunk'; operationId: number; chunk: string }
  | { type: 'generated'; operationId: number; response: string; tokenCount: number; elapsedMs: number }
  | { type: 'transcribed'; operationId: number; text: string; elapsedMs: number }
  | { type: 'synthesized'; operationId: number; samples: Float32Array; sampleRate: number; duration: number; elapsedMs: number }
  | { type: 'error'; operationId: number; error: string };
"#
}
