import { createHash, randomUUID } from 'node:crypto';
import { createServer } from 'node:http';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocketServer, WebSocket } from 'ws';

const root = dirname(fileURLToPath(import.meta.url));
const outputDirectory = process.env.MOCK_GAME_OUTPUT_DIRECTORY ? resolve(process.env.MOCK_GAME_OUTPUT_DIRECTORY) : join(root, 'test-output');
const protocol = 'gemtavern.rp_engine';
const protocolVersion = 3;
const socketPort = Number(process.env.RPENGINE_PORT ?? 38471);
const controlPort = Number(process.env.MOCK_GAME_CONTROL_PORT ?? 38472);
const allowedOrigins = new Set([
  'http://127.0.0.1:5173',
  'https://rpengine.gemtavern.com',
  'https://rp-engine.gemtavern.com',
]);
if (!Number.isInteger(socketPort) || socketPort < 1024 || socketPort > 65535) throw new Error('RPENGINE_PORT must be between 1024 and 65535.');
if (!Number.isInteger(controlPort) || controlPort < 1024 || controlPort > 65535) throw new Error('MOCK_GAME_CONTROL_PORT must be between 1024 and 65535.');

let sessionId;
let socket;
let lastCard;
let lastCardHash;
let activeRequestId;
let voiceCapture;
let capacity = { acceptingRequests: false, queueDepth: 0, queueLimit: 20 };
const pending = new Map();
const audio = new Map();
const microphoneAudio = new Map();
const events = [];

function canonical(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;
}
function hash(value) { return createHash('sha256').update(canonical(value)).digest('hex'); }
function envelope(type, payload = {}) {
  return { protocol, protocolVersion, type, messageId: randomUUID(), sessionId, timestamp: new Date().toISOString(), ...payload };
}
function log(direction, type, details) {
  events.push({ timestamp: new Date().toISOString(), direction, type, details });
  if (events.length > 500) events.splice(0, events.length - 500);
  process.stdout.write(`[${direction}] ${type}${details ? ` ${JSON.stringify(details)}` : ''}\n`);
}
function send(type, payload = {}) {
  if (!socket || socket.readyState !== WebSocket.OPEN) throw new Error('RPEngine PWA is not connected.');
  const message = envelope(type, payload);
  socket.send(JSON.stringify(message));
  log('game → pwa', type, payload);
  return message;
}

function pointer(value) { return value.replaceAll('~', '~0').replaceAll('/', '~1'); }
function diff(before, after, path = '') {
  if (canonical(before) === canonical(after)) return [];
  if (before && after && typeof before === 'object' && typeof after === 'object' && !Array.isArray(before) && !Array.isArray(after)) {
    const operations = [];
    for (const key of Object.keys(before).filter(key => !(key in after)).sort().reverse()) operations.push({ op: 'remove', path: `${path}/${pointer(key)}` });
    for (const key of Object.keys(after).filter(key => !(key in before)).sort()) operations.push({ op: 'add', path: `${path}/${pointer(key)}`, value: after[key] });
    for (const key of Object.keys(before).filter(key => key in after).sort()) operations.push(...diff(before[key], after[key], `${path}/${pointer(key)}`));
    return operations;
  }
  return [{ op: 'replace', path, value: after }];
}

function buildCard(input) {
  return {
    spec: 'chara_card_v2', spec_version: '2.0',
    data: {
      name: input.characterName || 'Ari',
      description: input.description || '{{char}} is an observant station engineer.',
      personality: input.personality || 'Calm, dryly funny, practical, and loyal.',
      scenario: input.scenario || '{{user}} and {{char}} are testing a live game integration.',
      first_mes: 'Connection established.',
      mes_example: '<START>\n{{user}}: Can you hear me?\n{{char}}: Loud and clear.',
      creator_notes: 'Generated by the RPEngine mock-game integration.',
      system_prompt: 'Portray {{char}} faithfully. Treat the latest event as immediate reality.',
      post_history_instructions: 'Never mention language models, prompts, or test infrastructure.',
      alternate_greetings: [],
      tags: ['test-character'], creator: 'RPEngine mock game', character_version: '1.0', extensions: {},
    },
  };
}

function createTransfer(mode, card) {
  const targetHash = hash(card);
  if (mode === 'snapshot') return { descriptor: { format: 'chara_card_v2', mode, snapshot: card, targetHash }, targetHash };
  if (!lastCard || !lastCardHash) throw new Error('Send a snapshot before using patch or reference mode.');
  if (mode === 'reference') {
    if (targetHash !== lastCardHash) throw new Error('Reference mode requires an unchanged card. Use patch or snapshot after editing it.');
    return { descriptor: { format: 'chara_card_v2', mode, targetHash }, targetHash };
  }
  return { descriptor: { format: 'chara_card_v2', mode: 'patch', patch: diff(lastCard, card), baseHash: lastCardHash, targetHash }, targetHash };
}

function submitReply(input, forcedSnapshot = false, existing) {
  const card = existing?.card ?? buildCard(input);
  const transfer = forcedSnapshot
    ? { descriptor: { format: 'chara_card_v2', mode: 'snapshot', snapshot: card, targetHash: hash(card) }, targetHash: hash(card) }
    : createTransfer(input.transferMode || 'snapshot', card);
  const requestId = existing?.requestId ?? randomUUID();
  const eventId = existing?.eventId ?? randomUUID();
  const request = {
    requestId, eventId, integrationId: 'mock-game', characterId: input.characterId || 'mock-character-1',
    event: {
      ...(input.eventText?.trim() ? { text: input.eventText } : {}),
      ...(input.eventAudio ? { audio: input.eventAudio } : {}),
    },
    output: input.outputMode === 'text'
      ? { modalities: ['text'], language: input.language || 'en' }
      : { modalities: ['text', 'audio'], language: input.language || 'en', audio: { model: 'gemtavern-supertonic-3', voice: input.voiceId || 'F4', format: 'pcm_s16le' } },
    player: { displayName: input.playerName || 'Player' }, card: transfer.descriptor,
  };
  pending.set(requestId, { kind: 'reply', requestId, eventId, input, card, request });
  lastCard = structuredClone(card);
  lastCardHash = transfer.targetHash;
  activeRequestId = requestId;
  send('reply.request', request);
  return requestId;
}

function submitVoiceCapture(input, forcedSnapshot = false, existing) {
  if (activeRequestId) throw new Error('Finish or cancel the active request before starting another voice capture.');
  const card = existing?.card ?? buildCard(input);
  const transfer = forcedSnapshot
    ? { descriptor: { format: 'chara_card_v2', mode: 'snapshot', snapshot: card, targetHash: hash(card) }, targetHash: hash(card) }
    : createTransfer(input.transferMode || 'snapshot', card);
  const requestId = existing?.requestId ?? randomUUID();
  const eventId = existing?.eventId ?? randomUUID();
  const request = {
    requestId, eventId, integrationId: 'mock-game', characterId: input.characterId || 'mock-character-1',
    output: input.outputMode === 'text'
      ? { modalities: ['text'], language: input.language || 'en' }
      : { modalities: ['text', 'audio'], language: input.language || 'en', audio: { model: 'gemtavern-supertonic-3', voice: input.voiceId || 'F4', format: 'pcm_s16le' } },
    player: { displayName: input.playerName || 'Player' }, card: transfer.descriptor,
    debug: { echoCapturedAudio: true, echoTranscript: true },
  };
  pending.set(requestId, { kind: 'voice', requestId, eventId, input, card, request });
  lastCard = structuredClone(card);
  lastCardHash = transfer.targetHash;
  activeRequestId = requestId;
  voiceCapture = { requestId, state: 'requested', seconds: 0, peak: 0, rms: 0, autoEndEnabled: false, message: 'Waiting for RPEngine to start browser microphone capture.' };
  send('voice.capture.start', request);
  return requestId;
}

async function receive(raw) {
  let message;
  try { message = JSON.parse(String(raw)); } catch { return log('pwa → game', 'invalid_json'); }
  if (message.protocol !== protocol || message.protocolVersion !== protocolVersion) return log('pwa → game', 'protocol_rejected', message);
  const isAudioChunk = typeof message.type === 'string' && message.type.endsWith('.audio.chunk');
  log('pwa → game', message.type, isAudioChunk ? { requestId: message.requestId, sequence: message.sequence, segmentSequence: message.segmentSequence, segmentChunkSequence: message.segmentChunkSequence, bytes: Buffer.from(message.data || '', 'base64').length } : message);
  if (message.type === 'capacity.update') capacity = { acceptingRequests: Boolean(message.acceptingRequests), queueDepth: Number(message.queueDepth), queueLimit: Number(message.queueLimit) };
  if (message.type === 'voice.capture.level' && voiceCapture?.requestId === message.requestId) {
    voiceCapture = { ...voiceCapture, seconds: Number(message.seconds) || 0, peak: Number(message.peak) || 0, rms: Number(message.rms) || 0 };
  }
  if (message.type === 'voice.capture.state' && voiceCapture?.requestId === message.requestId) {
    voiceCapture = { ...voiceCapture, state: String(message.state || 'listening'), seconds: Number(message.seconds) || 0, autoEndEnabled: message.autoEndEnabled !== false, message: String(message.message || '') };
  }
  if (message.type === 'reply.audio.start') audio.set(message.requestId, { sampleRate: message.sampleRate, chunks: new Map() });
  if (message.type === 'reply.audio.chunk') audio.get(message.requestId)?.chunks.set(message.sequence, Buffer.from(message.data, 'base64'));
  if (message.type === 'reply.audio.completed') await saveAudio(message.requestId, message);
  if (message.type === 'voice.capture.audio.start') microphoneAudio.set(message.requestId, { sampleRate: message.sampleRate, chunks: new Map() });
  if (message.type === 'voice.capture.audio.chunk') microphoneAudio.get(message.requestId)?.chunks.set(message.sequence, Buffer.from(message.data, 'base64'));
  if (message.type === 'voice.capture.audio.completed') await saveMicrophoneAudio(message.requestId, message);
  if (message.type === 'voice.capture.transcript') await saveMoonshineTranscript(message.requestId, message);
  if (message.type === 'request.error' && message.code === 'card_resync_required') {
    const request = pending.get(message.requestId);
    if (request?.kind === 'voice') { activeRequestId = undefined; submitVoiceCapture(request.input, true, request); }
    else if (request) submitReply(request.input, true, request);
  }
  if (['reply.completed', 'reply.cancelled'].includes(message.type)) {
    pending.delete(message.requestId);
    if (activeRequestId === message.requestId) activeRequestId = undefined;
    if (voiceCapture?.requestId === message.requestId) {
      voiceCapture = {
        ...voiceCapture,
        state: message.type === 'reply.completed' ? 'completed' : 'cancelled',
        message: captureArtifactMessage(voiceCapture),
      };
    }
  }
  if (message.type === 'request.error' && voiceCapture?.requestId === message.requestId && message.code !== 'card_resync_required') {
    pending.delete(message.requestId);
    if (activeRequestId === message.requestId) activeRequestId = undefined;
    voiceCapture = { ...voiceCapture, state: 'error', message: String(message.message || 'Voice capture failed.') };
  }
}

async function saveAudio(requestId, completed) {
  const result = audio.get(requestId);
  if (!result) return;
  const sequences = [...result.chunks.keys()].sort((a, b) => a - b);
  if (sequences.length !== completed.chunkCount || sequences.some((value, index) => value !== index)) return log('mock', 'audio_invalid', { requestId, sequences });
  const pcm = Buffer.concat(sequences.map(sequence => result.chunks.get(sequence)));
  if (pcm.length !== completed.totalBytes) return log('mock', 'audio_invalid', { requestId, expectedBytes: completed.totalBytes, actualBytes: pcm.length });
  const wav = wavFile(pcm, result.sampleRate);
  await mkdir(outputDirectory, { recursive: true });
  const path = join(outputDirectory, `${requestId}.wav`);
  await writeFile(path, wav);
  audio.delete(requestId);
  log('mock', 'audio_saved', { requestId, path, bytes: pcm.length, sampleRate: result.sampleRate });
}

async function saveMicrophoneAudio(requestId, completed) {
  const result = microphoneAudio.get(requestId);
  if (!result) return;
  const sequences = [...result.chunks.keys()].sort((a, b) => a - b);
  if (sequences.length !== completed.chunkCount || sequences.some((value, index) => value !== index)) return log('mock', 'microphone_audio_invalid', { requestId, sequences });
  const pcm = Buffer.concat(sequences.map(sequence => result.chunks.get(sequence)));
  if (pcm.length !== completed.totalBytes) return log('mock', 'microphone_audio_invalid', { requestId, expectedBytes: completed.totalBytes, actualBytes: pcm.length });
  const wav = wavFile(pcm, result.sampleRate);
  await mkdir(outputDirectory, { recursive: true });
  const path = join(outputDirectory, `${requestId}-microphone.wav`);
  await writeFile(path, wav);
  microphoneAudio.delete(requestId);
  if (voiceCapture?.requestId === requestId) {
    voiceCapture = { ...voiceCapture, recordingPath: path };
    voiceCapture.message = captureArtifactMessage(voiceCapture);
  }
  log('mock', 'microphone_audio_saved', { requestId, path, bytes: pcm.length, sampleRate: result.sampleRate });
}

async function saveMoonshineTranscript(requestId, result) {
  const text = String(result.text ?? '');
  await mkdir(outputDirectory, { recursive: true });
  const path = join(outputDirectory, `${requestId}-moonshine.txt`);
  await writeFile(path, `${text}\n`, 'utf8');
  if (voiceCapture?.requestId === requestId) {
    voiceCapture = { ...voiceCapture, transcript: text, transcriptLanguage: String(result.language || ''), transcriptElapsedMs: Number(result.elapsedMs) || 0, transcriptPath: path };
    voiceCapture.message = captureArtifactMessage(voiceCapture);
  }
  log('mock', 'moonshine_transcript_saved', { requestId, path, text, language: result.language, elapsedMs: result.elapsedMs });
}

function captureArtifactMessage(capture) {
  const artifacts = [];
  if (capture?.recordingPath) artifacts.push(`Microphone WAV saved: ${capture.recordingPath}`);
  if (capture?.transcriptPath) artifacts.push(`Moonshine transcript saved: ${capture.transcriptPath}`);
  return artifacts.join(' · ');
}

function wavFile(pcm, sampleRate) {
  const header = Buffer.alloc(44);
  header.write('RIFF', 0); header.writeUInt32LE(36 + pcm.length, 4); header.write('WAVE', 8); header.write('fmt ', 12);
  header.writeUInt32LE(16, 16); header.writeUInt16LE(1, 20); header.writeUInt16LE(1, 22); header.writeUInt32LE(sampleRate, 24);
  header.writeUInt32LE(sampleRate * 2, 28); header.writeUInt16LE(2, 32); header.writeUInt16LE(16, 34); header.write('data', 36); header.writeUInt32LE(pcm.length, 40);
  return Buffer.concat([header, pcm]);
}

const httpServer = createServer(async (request, response) => {
  try {
    const url = new URL(request.url, `http://127.0.0.1:${controlPort}`);
    if (url.pathname === '/api/state') return json(response, 200, state());
    if (url.pathname === '/api/request' && request.method === 'POST') {
      const input = await body(request);
      return json(response, 200, { requestId: submitReply(input), state: state() });
    }
    if (url.pathname === '/api/cancel' && request.method === 'POST') {
      const input = await body(request); const requestId = input.requestId || activeRequestId;
      if (!requestId) throw new Error('There is no active request to cancel.');
      send('request.cancel', { requestId }); return json(response, 200, { requestId });
    }
    if (url.pathname === '/api/voice/start' && request.method === 'POST') {
      if (!socket || socket.readyState !== WebSocket.OPEN) throw new Error('RPEngine PWA is not connected.');
      if (!capacity.acceptingRequests) throw new Error('RPEngine is not ready to accept voice capture requests. Start RPEngine and enable its microphone first.');
      const input = await body(request);
      const requestId = submitVoiceCapture(input);
      return json(response, 200, { requestId, state: state() });
    }
    if (url.pathname === '/api/voice/stop' && request.method === 'POST') {
      const input = await body(request); const requestId = input.requestId || voiceCapture?.requestId;
      if (!requestId || activeRequestId !== requestId) throw new Error('There is no active voice capture to stop.');
      send('voice.capture.stop', { requestId });
      voiceCapture = { ...voiceCapture, state: 'stopping', message: 'Waiting for RPEngine to finalize the recording.' };
      return json(response, 200, { requestId, state: state() });
    }
    if (url.pathname === '/api/voice/cancel' && request.method === 'POST') {
      const input = await body(request); const requestId = input.requestId || voiceCapture?.requestId;
      if (!requestId || activeRequestId !== requestId) throw new Error('There is no active voice capture to cancel.');
      send('voice.capture.cancel', { requestId });
      return json(response, 200, { requestId, state: state() });
    }
    const file = url.pathname === '/' ? 'index.html' : url.pathname.slice(1);
    if (!['index.html', 'app.js', 'styles.css'].includes(file)) return json(response, 404, { error: 'Not found' });
    const content = await readFile(join(root, file));
    response.writeHead(200, { 'Content-Type': file.endsWith('.html') ? 'text/html; charset=utf-8' : file.endsWith('.js') ? 'text/javascript; charset=utf-8' : 'text/css; charset=utf-8', 'Cache-Control': 'no-store' });
    response.end(content);
  } catch (error) { json(response, 400, { error: error instanceof Error ? error.message : String(error) }); }
});

const wsServer = new WebSocketServer({ host: '127.0.0.1', port: socketPort, path: '/rp-engine/socket', maxPayload: 8 * 1024 * 1024 });
wsServer.on('connection', (candidate, request) => {
  if (!allowedOrigins.has(request.headers.origin || '')) { candidate.close(1008, 'Origin rejected'); return; }
  candidate.once('message', raw => {
    let hello;
    try { hello = JSON.parse(String(raw)); } catch { candidate.close(1008, 'Invalid hello'); return; }
    if (hello.protocol !== protocol || hello.protocolVersion !== 3 || hello.type !== 'hello') { candidate.close(1008, 'Invalid hello'); return; }
    sessionId = randomUUID();
    socket?.close(3000, 'Superseded'); socket = candidate;
    send('welcome', { serverVersion: 'mock-game-1.0' });
    candidate.on('message', receive);
    candidate.on('close', () => { if (socket === candidate) { socket = undefined; sessionId = undefined; lastCard = undefined; lastCardHash = undefined; } });
  });
});

function state() {
  return { connected: socket?.readyState === WebSocket.OPEN, sessionId, capacity, activeRequestId, voiceCapture, clientUrl: `http://127.0.0.1:5173/#port=${socketPort}`, socketPort, lastCardHash, events: events.slice(-100) };
}
async function body(request) { const chunks = []; for await (const chunk of request) chunks.push(chunk); return JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}'); }
function json(response, status, value) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); response.end(JSON.stringify(value)); }

httpServer.listen(controlPort, '127.0.0.1', () => {
  process.stdout.write(`Mock game control: http://127.0.0.1:${controlPort}\n`);
  process.stdout.write(`RPEngine socket: ws://127.0.0.1:${socketPort}/rp-engine/socket\n`);
});

for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => { wsServer.close(); httpServer.close(() => process.exit(0)); });
